# Generated by Django 6.1.1 on 2026-09-28 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment created'), ('DRIVER_ASSIGNED', 'Driver assigned'), ('SHIPMENT_STATUS_CHANGED', 'Shipment status changed'), ('DELIVERY_DELAYED', 'Delivery delayed'), ('PAYMENT_UPDATED', 'Payment updated'), ('COMPLAINT_UPDATED', 'Complaint updated'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='Id of the related object (shipment, payment, complaint, ...).', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text="The user this notification is for. Left null for system-wide broadcast notifications (notification_type=SYSTEM) that aren't targeted at one specific user.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
